### ISSUE TITLE
load / pull missing.

### ISSUE THREAD

**Issue by Dimrok** [docker/app#192]
(experimental: off)

You can save and push but not load and pull.

## How to reproduce
```
14:37 $ docker-app
Build and deploy Docker applications.

Usage:
  docker-app [command]

Available Commands:
  deploy      Deploy or update an application
  helm        Generate a Helm chart
  help        Help about any command
  init        Start building a Docker application
  inspect     Shows metadata and settings for a given application
  push        Push the application to a registry
  render      Render the Compose file for the application
  save        Save the application as an image to the docker daemon(in preparation for push)
  version     Print version information
```

## Version

```
docker-app version
Version:      0.1.0-162-g9b311d2
Git commit:   9b311d2
Build time:   2018-06-07T12:36:50.253486313+00:00
OS/Arch:      linux/amd64
Experimental: off
Renderers:    none
```

**Comment by devzsolt** [comment]
@garethr could you please explain what's the workflow then? Why do we have push if it can't be pulled? How should we retrieve app packages?

**Comment by garethr** [comment]
@devzsolt `push` is explicit, in that you will often want to store you applications on Hub or another registry. `pull` is implicit (like with `docker run`) so whenever you `deploy` or `render` or `inspect` an application it will automatically be pulled.

This has one downside, that we don't have a local cache of applications at present. This is likely to change in the future but it's an optimisation rather than a fundamental.

**Comment by mnottale** [comment]
You can still perform a pull-like operation by using split and merge if you really need the app locally.

**Comment by devzsolt** [comment]
Thanks for the clarification, makes sense.
